# ===================================================
#
# PLIK KONFIGURACYJNY
#
# ====================================================

#FORMAT
message-color: "&c"
message-format: "&8(%CSurvivalCore&8) &7{MESSAGE}"

#PERMISJE
survival-core-permission-message: "Nie posiadasz %Cpermisji &7aby uzyc tej komendy &8(%C{%0}&8)"

#DOLACZANIE
message-join-first-time: "&8[&a+&8] &7Gracz %C{%0} &7dolaczyl po raz pierwszy!"
message-join: "&8[&a+&8] &7Gracz %C{%0} &7dolaczyl na serwer!"

#KOMENDA POMOC:
message-help: "&8============= [ &l%CPOMOC &r&8] ============= {LINE}&l%C/zglos &r&8- &7komenda do zgloszenia gracza &r{LINE}&8============= [ &l%CPOMOC &r&8] ============="

message-report-use: "Poprawne uzycie to %C/zglos &8(%Cwiadomosc&8)"
message-report-cooldown: "Nastepne zgloszenie mozesz wyslac za %C{%0} &7sekund!"
message-report-succes: "Pomyslnie wyslano zgloszenie!"
report-message-admin: "&8(&1HelpOP&8) &7{%0}&8: &1{%1}"

#SAY 
message-say-use: "Poprawne uzycie to %C/say &8(%Cwiadomosc&8)"
message-say-chat: "&8» &7{%0}"
